server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/event_booking_db
    username: event_booking_user
    password: event_booking_password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        enable_lazy_load_no_trans: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  profiles:
    active: development
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

app:
  upload-directory: event_booking_system-uploads
  folder-temp: ./event_booking_system-temp/

logging:
  level:
    com.sinaukoding.event_booking_system: TRACE

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    defaultModelsExpandDepth: -1
    docExpansion: none
    tagsSorter: alpha
    operationsSorter: alpha